from __future__ import annotations

import html
import re
import textwrap
import zipfile
from dataclasses import dataclass
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape


FORBIDDEN_EMPLOYER_FACING_MARKERS = (
    "```",
    "{",
    "}",
    "evidence brick",
    "truth guard",
    "polish check",
    "confidence score",
    "unsupported requirement",
    "as an ai",
    "i recommend",
    "suggested",
    "generated by",
    "tailored for",
    "model note:",
)


@dataclass(frozen=True)
class ResumeRenderResult:
    text_path: Path
    html_path: Path
    docx_path: Path
    pdf_path: Path


def validate_employer_facing_resume(text: str) -> None:
    normalized = text.strip()
    if not normalized:
        raise ValueError("Employer-facing resume text is empty")
    lowered = normalized.lower()
    for marker in FORBIDDEN_EMPLOYER_FACING_MARKERS:
        if marker in lowered:
            raise ValueError(f"Employer-facing resume contains forbidden marker: {marker}")
    if len(normalized.splitlines()) < 6:
        raise ValueError("Employer-facing resume text is too short to render safely")


def _clean_lines(text: str) -> list[str]:
    return [line.rstrip() for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]


def _html_document(text: str) -> str:
    body_lines = []
    for line in _clean_lines(text):
        if not line.strip():
            body_lines.append("<br>")
        else:
            body_lines.append(f"<p>{html.escape(line)}</p>")
    return "\n".join(
        [
            "<!doctype html>",
            "<html>",
            "<head>",
            '<meta charset="utf-8">',
            "<title>Resume</title>",
            "<style>",
            "body { font-family: Georgia, 'Times New Roman', serif; color: #111; line-height: 1.35; margin: 48px; }",
            "p { margin: 0 0 6px; }",
            "</style>",
            "</head>",
            "<body>",
            *body_lines,
            "</body>",
            "</html>",
        ]
    )


def _docx_document_xml(text: str) -> str:
    paragraphs = []
    for line in _clean_lines(text):
        if line.strip():
            paragraphs.append(f"<w:p><w:r><w:t>{xml_escape(line)}</w:t></w:r></w:p>")
        else:
            paragraphs.append("<w:p/>")
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        "<w:body>"
        + "".join(paragraphs)
        + '<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/></w:sectPr>'
        "</w:body></w:document>"
    )


def _write_docx(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "[Content_Types].xml",
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            '<Default Extension="xml" ContentType="application/xml"/>'
            '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
            "</Types>",
        )
        archive.writestr(
            "_rels/.rels",
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
            "</Relationships>",
        )
        archive.writestr("word/document.xml", _docx_document_xml(text))


def _pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _write_simple_pdf(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    wrapped_lines: list[str] = []
    for line in _clean_lines(text):
        if not line.strip():
            wrapped_lines.append("")
            continue
        wrapped = textwrap.wrap(line, width=96, replace_whitespace=False, drop_whitespace=False)
        wrapped_lines.extend(wrapped or [""])

    lines_per_page = 52
    pages = [wrapped_lines[index : index + lines_per_page] for index in range(0, len(wrapped_lines), lines_per_page)]
    if not pages:
        pages = [[""]]

    objects: list[bytes] = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    page_object_ids: list[int] = []
    for page_lines in pages:
        content_lines = ["BT", "/F1 10 Tf", "50 760 Td", "14 TL"]
        for line in page_lines:
            safe = _pdf_escape(re.sub(r"[^\x09\x0a\x0d\x20-\x7e]", "", line))
            content_lines.append(f"({safe}) Tj")
            content_lines.append("T*")
        content_lines.append("ET")
        stream = "\n".join(content_lines).encode("ascii", errors="ignore")
        page_object_id = len(objects) + 1
        content_object_id = page_object_id + 1
        page_object_ids.append(page_object_id)
        objects.append(
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents {content_object_id} 0 R >>".encode(
                "ascii"
            )
        )
        objects.append(b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"\nendstream")

    kids = " ".join(f"{page_id} 0 R" for page_id in page_object_ids)
    objects[1] = f"<< /Type /Pages /Kids [{kids}] /Count {len(page_object_ids)} >>".encode("ascii")

    output = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(output))
        output.extend(f"{index} 0 obj\n".encode("ascii"))
        output.extend(obj)
        output.extend(b"\nendobj\n")
    xref_offset = len(output)
    output.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    output.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.extend(
        (
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_offset}\n%%EOF\n"
        ).encode("ascii")
    )
    path.write_bytes(bytes(output))


class ResumeRenderer:
    def render_all(self, *, employer_facing_resume_text: str, output_dir: str | Path) -> ResumeRenderResult:
        validate_employer_facing_resume(employer_facing_resume_text)
        root = Path(output_dir)
        root.mkdir(parents=True, exist_ok=True)

        text_path = root / "tailored_resume.txt"
        html_path = root / "tailored_resume.html"
        docx_path = root / "tailored_resume.docx"
        pdf_path = root / "tailored_resume.pdf"

        text_path.write_text(employer_facing_resume_text, encoding="utf-8")
        html_path.write_text(_html_document(employer_facing_resume_text), encoding="utf-8")
        _write_docx(docx_path, employer_facing_resume_text)
        _write_simple_pdf(pdf_path, employer_facing_resume_text)

        return ResumeRenderResult(
            text_path=text_path,
            html_path=html_path,
            docx_path=docx_path,
            pdf_path=pdf_path,
        )
